# -*- coding: utf-8 -*-
"""finalberthyp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1At62q0uryj-KjCzRugyZkhktGGc2PKkM
"""

pip install tensorflow-gpu==1.15.2

!pip install deeppavlov

!python -m deeppavlov install ner_ontonotes_bert_mult

from deeppavlov import configs, build_model,train_model

from deeppavlov import configs, build_model
import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings("ignore")

ner_model = build_model(configs.ner.ner_ontonotes_bert_mult, download=True)

from google.colab import files

files.upload()

"""Разбиение по n элементов

"""

def chunks(iterable, count):

 
    return zip(*[iter(iterable)] * count)

text_tokens = list(chunks(text_tokens,5))

ner_model(text_tokens)

df =pd.read_csv('All_good_data(need_to_process).csv')

df_hyp = pd.DataFrame()

money = np.zeros(10331)
date = np.zeros(10331)
time = np.zeros(10331)
person = np.zeros(10331)
location = np.zeros(10331)
organization = np.zeros(10331)
gpe = np.zeros(10331) #города, страны, области
facility = np.zeros(10331) #Постройки,мосты,дороги т.д.

text_tokens = sent_tokenize(df['responsibleperson_msg'][7])
text_tokens[0]

from nltk.tokenize import sent_tokenize, word_tokenize


for i in range(len(df['responsibleperson_msg'])-1):
    t = str(df['responsibleperson_msg'][i])
    t = sent_tokenize(t)
    print(i)
    for j in range(len(t)-1):
        if len(t[j]) < 512:
            NER = ner_model([t[j]])
            if 'B-LOCATION' in NER[1][0]:
                location[i] += 1
            if 'B-MONEY' in NER[1][0]:
                money[i] += 1
            if 'B-DATE' in NER[1][0]:
                date[i] += 1
            if 'B-TIME' in NER[1][0]:
                time[i] += 1
            if 'B-PERSON' in NER[1][0]:
                person[i] += 1
            if 'B-ORGANIZATION' in NER[1][0]:
                organization[i] += 1
            if 'B-GPE' in NER[1][0]:
              gpe[i] = +1
            if 'B-FAC':
              facility[i] += 1
df_hyp['HypLocation'] = location
df_hyp['HypMoney'] = money
df_hyp['HypDate'] = date
df_hyp['HypTime'] = time
df_hyp['HypPerson'] = person
df_hyp['HypOrganization'] = organization
df_hyp['HypGPE'] = gpe
df_hyp['HypFacility'] = facility

!pip install --upgrade pandas

dfhyp

dfhyp = df_hyp
dfhyp.to_csv('dfhyp.csv')
files.download('dfhyp.csv')